CHAT_TRANSLATION_AGENT_APID = "agent-1bad27aabaac439da678f31d53855b5d"
CHAT_REPLY_SUGGESTION_AGENT_APID = "agent-5a43bda9e1304108a1a78a3575a44e27"
CHAT_CUSTOMER_STAGE_AGENT_APID = "agent-f6fb1e0ddff44d27bb3e19e243a70584"
CHAT_CUSTOMER_INTENT_AGENT_APID = "agent-c9b80fdfad234392b55d84de93a186ae"

CHAT_TRANSLATION_RESULT_TOOL = "process_chat_translation_result"
CHAT_REPLY_SUGGESTION_RESULT_TOOL = "process_chat_suggestion_result"
CHAT_CUSTOMER_STAGE_RESULT_TOOL = "process_customer_stage_analysis_result"
CHAT_CUSTOMER_INTENT_RESULT_TOOL = "process_customer_intent_analysis_result"

SYSTEM_AGENT_TOOLS: dict[str, list[str]] = {
    CHAT_TRANSLATION_AGENT_APID: [CHAT_TRANSLATION_RESULT_TOOL],
    CHAT_REPLY_SUGGESTION_AGENT_APID: [CHAT_REPLY_SUGGESTION_RESULT_TOOL],
    CHAT_CUSTOMER_STAGE_AGENT_APID: [CHAT_CUSTOMER_STAGE_RESULT_TOOL],
    CHAT_CUSTOMER_INTENT_AGENT_APID: [CHAT_CUSTOMER_INTENT_RESULT_TOOL],
}

SYSTEM_AGENT_APIDS = frozenset(SYSTEM_AGENT_TOOLS)
SYSTEM_AGENT_ONLY_TOOLS = frozenset(
    tool_name for tool_names in SYSTEM_AGENT_TOOLS.values() for tool_name in tool_names
)


__all__ = [
    "CHAT_CUSTOMER_INTENT_AGENT_APID",
    "CHAT_CUSTOMER_INTENT_RESULT_TOOL",
    "CHAT_CUSTOMER_STAGE_AGENT_APID",
    "CHAT_CUSTOMER_STAGE_RESULT_TOOL",
    "CHAT_REPLY_SUGGESTION_AGENT_APID",
    "CHAT_REPLY_SUGGESTION_RESULT_TOOL",
    "CHAT_TRANSLATION_AGENT_APID",
    "CHAT_TRANSLATION_RESULT_TOOL",
    "SYSTEM_AGENT_APIDS",
    "SYSTEM_AGENT_ONLY_TOOLS",
    "SYSTEM_AGENT_TOOLS",
]
